
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true  
    env_file:
      - .env
    networks:
      proxy:
    ports:
      - 80:80
      - 443:443
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`server-1.himanshu-gunwant.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.traefik.tls.certresolver=tlsResolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.service=api@internal"

  campaign-app:
    image: campaign-app
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.campaign.rule=PathPrefix(`/api/v1/campaign`)"
      - "traefik.http.services.campaign.loadbalancer.server.port=3000"
      - "traefik.http.routers.campaign.entrypoints=websecure"
      - "traefik.http.routers.campaign.tls.certresolver=tlsResolver"

  globetrotter-app:
    image: globetrotter-app
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.globetrotter.rule=PathPrefix(`/api/v1/globetrotter`)"
      - "traefik.http.services.globetrotter.loadbalancer.server.port=3000"
      - "traefik.http.routers.globetrotter.entrypoints=websecure"
      - "traefik.http.routers.globetrotter.tls.certresolver=tlsResolver"

  api-snappy:
    image: api-snappy
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snappy.rule=PathPrefix(`/api/v1/snappy`)"
      - "traefik.http.services.snappy.loadbalancer.server.port=5000"
      - "traefik.http.routers.snappy.entrypoints=websecure"
      - "traefik.http.routers.snappy.tls.certresolver=tlsResolver"
      - "traefik.http.middlewares.snappy-strip.stripprefix.prefixes=/api/v1/snappy"
      - "traefik.http.routers.snappy.middlewares=snappy-strip"

  portainer_agent:
    image: portainer/agent:2.27.1
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host