services:
  campaign-app:
    image: hgunwant2312/zenodeck-campaign:latest
    env_file:
      - .env.campaign
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.campaign.entrypoints=websecure"
      - "traefik.http.routers.campaign.rule=PathPrefix(`/api/v1/campaign`)"
      - "traefik.http.services.campaign.loadbalancer.server.port=3000"
      - "traefik.http.routers.campaign.tls.certresolver=tlsResolver"

  globetrotter-app:
    image: hgunwant2312/globetrotter
    env_file:
      - .env.globetrotter
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.globetrotter.entrypoints=websecure"
      - "traefik.http.routers.globetrotter.rule=PathPrefix(`/api/v1/globetrotter`)"
      - "traefik.http.services.globetrotter.loadbalancer.server.port=3000"
      - "traefik.http.routers.globetrotter.tls.certresolver=tlsResolver"

  api-snappy:
    image: hgunwant2312/api-snappy
    env_file:
      - .env.api-snappy
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snappy.entrypoints=websecure"
      - "traefik.http.routers.snappy.rule=PathPrefix(`/api/v1/snappy`)"
      - "traefik.http.services.snappy.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.snappy-strip.stripprefix.prefixes=/api/v1/snappy"
      - "traefik.http.routers.snappy.middlewares=snappy-strip"
      - "traefik.http.routers.snappy.tls.certresolver=tlsResolver"

  portainer_agent:
    image: portainer/agent:2.27.1
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    environment:
      - AGENT_SECRET=${PORTAINER_AGENT_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

networks:
  proxy:
    external: true