api:
  dashboard: true
  debug: false

tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: tlsResolver
        domain:
          main: server-1.himanshu-gunwant.com

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  tlsResolver:
    acme:
      email: info@himanshu-gunwant.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"