services:
  nginx:
    image: nginx:1.27.3-alpine-slim
    restart: always
    ports:
      - "443:80"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - campaign-app

  campaign-app:
    image: hgunwant2312/zenodeck-campaign:latest
    env_file:
      - .env.campaign
