services:
  traefik:
    image: traefik:v3.6

    env_file:
      - .env

    networks:
      - traefik_proxy

    ports:
      - target: 80
        published: 80
        mode: ingress
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/traefik/acme.json:/acme.json
      - /var/lib/traefik/conf:/var/lib/traefik/conf
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yaml:/traefik.yaml:ro

    deploy:
      mode: replicated
      replicas: 1
      placement:

        constraints:
          - node.role == manager

      labels:
        - "traefik.enable=true"

        # Dashboard router
        - "traefik.http.routers.dashboard.rule=Host(`traefik.himanshu-gunwant.com`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=tlsResolver"

        # Basic‑auth middleware
        # - "traefik.http.middlewares.dashboard-auth.basicauth.users=<PASTE_HASH_HERE>"
        # - "traefik.http.routers.dashboard.middlewares=dashboard-auth@swarm"

        # Service hint
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  traefik_proxy:
    name: traefik_proxy
    driver: overlay
    attachable: true