services:
  traefik:
    image: traefik:latest

    env_file:
      - .env

    networks:
      - proxy

    ports:
      - target: 80
        published: 80
        mode: ingress
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/traefik/acme.json:/acme.json
      - /var/lib/traefik/conf:/var/lib/traefik/conf
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yaml:/traefik.yaml:ro

    command:
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik_proxy"
      - "--log.level=DEBUG"
      - "--accesslog=true"

    deploy:
      placement:
        constraints:
          - node.labels.arm == true
      restart_policy:
        condition: any

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.himanshu-gunwant.com`)"
    #  - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.traefik.tls.certresolver=tlsResolver"
    #  - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  proxy:
    driver: overlay
    attachable: true